stages:
  - build-and-test
  - benchmark

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_BIN: /home/gitlab-runner/.local/graal-core/bin/java
  JVMCI_VERSION_CHECK: ignore

before_script:
  - git submodule update --init

build_and_test_job:
  stage: build-and-test
  tags: [benchmarks, infinity]
  script:
    - make test

benchmark_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - make
    - export EXP=`if [[ "$CI_BUILD_REF_NAME" = "master" ]]; then echo ""; else echo "-exp"; fi`; rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=TruffleSOM --branch=master core-lib/codespeed.conf TruffleSOM${EXP}
